# Generated by scripts/generate-homebrew-formula.sh -- do not edit by hand.
class Droidagent < Formula
  desc "Android development MCP server: Gradle, adb, logcat, crash triage, Perfetto"
  homepage "https://github.com/iVamsi/droid-agent-kit"
  url "https://github.com/iVamsi/droid-agent-kit/releases/download/v0.2.6-alpha/droidagent-cli-0.2.6-alpha.jar", using: :nounzip
  sha256 "7e0672d2fe7a9120ebfdd60ae41b6efb6b49c44454531c8cff66ac62e1988c99"
  license "Apache-2.0"
  version "0.2.6-alpha"

  depends_on "openjdk@17"

  def install
    libexec.install "droidagent-cli-0.2.6-alpha.jar"
    (bin/"droidagent").write <<~SH
      #!/bin/bash
      exec "#{Formula["openjdk@17"].opt_bin}/java" -jar "#{libexec}/droidagent-cli-0.2.6-alpha.jar" "$@"
    SH
    chmod 0755, bin/"droidagent"
  end

  def caveats
    <<~EOS
      Register the MCP server with your agent:
        droidagent install-mcp

      Check your environment first if anything misbehaves:
        droidagent doctor
    EOS
  end

  test do
    # Exercises the real entry point: the wrapper must find the JRE and the jar must run.
    # Deliberately only --help -- the CLI has no --version flag, and asserting one would fail
    #  on every install.
    output = shell_output("#{bin}/droidagent --help")
    assert_match "serve-mcp", output
    assert_match "doctor", output
  end
end
