# Generated by scripts/generate-homebrew-formula.sh -- do not edit by hand.
class Droidagent < Formula
  desc "Android development MCP server: Gradle, adb, logcat, crash triage, Perfetto"
  homepage "https://github.com/iVamsi/droid-agent-kit"
  url "https://github.com/iVamsi/droid-agent-kit/releases/download/v0.3.0-alpha/droidagent-cli-0.3.0-alpha.jar", using: :nounzip
  sha256 "03d86a8916f790c9f9ae8eeaba5ed6b7c8c0d464ce83f116fc2c67f0f47680e5"
  license "Apache-2.0"
  version "0.3.0-alpha"

  depends_on "openjdk@17"

  def install
    libexec.install "droidagent-cli-0.3.0-alpha.jar"
    (bin/"droidagent").write <<~SH
      #!/bin/bash
      exec "#{Formula["openjdk@17"].opt_bin}/java" -jar "#{libexec}/droidagent-cli-0.3.0-alpha.jar" "$@"
    SH
    chmod 0755, bin/"droidagent"
  end

  def caveats
    <<~EOS
      Register the MCP server with your agent:
        droidagent install-mcp

      Check your environment first if anything misbehaves:
        droidagent doctor
    EOS
  end

  test do
    # Exercises the real entry point: the wrapper must find the JRE and the jar must run.
    # Deliberately only --help -- the CLI has no --version flag, and asserting one would fail
    # `brew test` on every install.
    output = shell_output("#{bin}/droidagent --help")
    assert_match "serve-mcp", output
    assert_match "doctor", output
  end
end
